name: 'Delete old artifacts'
on:
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: self-hosted
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0 # Setting this to 0 will delete all artifacts
